parallel-jobs = 1
compression-level = 9
remove-rv-integrations-checks = true

rv-brand = ""

cli-source = "j-hc/revanced-cli"
cli-version = "dev"

patches-source = "anddea/revanced-patches"
patches-version = "dev"

#========== YouTube ==========#

[YouTube-Premium]
enabled = true
app-name = "YouTube Premium"
build-mode = "apk"
version = "auto"
arch = "arm64-v8a"
riplib = false

patcher-args = """\
  --rip-lib x86_64 --rip-lib x86 --rip-lib armeabi-v7a \
  -e 'Change version code' \
  -e 'GmsCore support' -OpackageNameYouTube='h1toru.rvm.ytp' \
  -e 'Custom branding name for YouTube' -OappName='YouTube Premium' \
  -d 'Custom branding icon for YouTube' \
  -d 'Custom header for YouTube' \
  -e 'Settings for YouTube' -OrvxSettingsLabel='Premium options' -OinsertPosition='About' \
  -e 'Theme' -OdarkThemeBackgroundColor='#000000' -OlightThemeBackgroundColor='#FFFFFF' \
  \
  -e 'Return YouTube Dislike' \
  -e 'Return YouTube Username' \
  -e 'SponsorBlock' \
  -d 'Alternative thumbnails' \
  -d 'Enable debug logging' \
  -d 'Translations for YouTube' \
  -d 'Set Transcript Cookies' \
  -d 'Disable layout updates' \
  -d 'Spoof app version' \
  -d 'Enable gradient loading screen' \
  -d 'Force player buttons background' \
  -d 'Hide Shorts dimming' \
  -d 'Custom double tap length' \
  -d 'Hide shortcuts' \
  """

# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/core-apks/apks/com.google.android.youtube"

#========== Spotify ==========#

[Spotify]
enabled = true
app-name = "Spotify"
version = "auto"
arch = "arm64-v8a"
riplib = false

patches-source = "anddea/revanced-patches"
patches-version = "dev"

patcher-args = """\
  --rip-lib x86_64 --rip-lib x86 --rip-lib armeabi-v7a \
  -d 'Custom theme' \
  -d 'Lyrics search' \
  """
# -e 'Custom theme' -ObackgroundColor='#FF000000' -OenableBackgroundColorSecondary=true -ObackgroundColorSecondary='#FF121212' \

uptodown-dlurl = "https://spotify.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
